#!/usr/bin/env python

import sys
import traceback
import argparse
from pathlib import Path

import numpy as np

import PyPDF2 as pypdf

import qrcode

from PIL import Image, ImageDraw, ImageFont


def save_qr_as_pdf(basename, qr_data, qr_size, font):
    QR = qrcode.make(qr_data)
    QR.save(basename + '.png')
    img = Image.open(basename + '.png').convert('L')
    # Resize assuming 72 dpi
    dpi = 72
    w0, h0 = img.size
    ratio = qr_size / (w0 / dpi)
    w, h = round(w0 * ratio), round(h0 * ratio)
    img = img.resize((w, h), resample=Image.NEAREST)
    # Add bottom margin for text.
    wp, hp = w, h + dpi // 2
    padded = Image.new('L', (wp, hp), color=(255,))
    padded.paste(img, (round((wp - w) / 2), 0))
    # Add border and text.
    draw = ImageDraw.Draw(padded)
    draw.rectangle((1, 1, w - 2, h - 2), outline='black', fill=None)
    wt, ht = draw.textsize(qr_data, font=font)
    draw.text(((wp - wt) // 2, (h + hp - ht) // 2), qr_data, (0,), font=font)
    # Save as QR overlay as PDF.
    padded.save(basename + '.pdf', format='pdf')


def main():
    # Parse command-line arguments.
    parser = argparse.ArgumentParser(
        description='Prepare handouts for recording attendance.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('template', help='Template PDF file to use.')
    parser.add_argument('-v', '--verbose', action='store_true',
        help='Print verbose progress report')
    parser.add_argument(
        '-n', '--num-copies', type=int, metavar='N', required=True,
        help='Number of copies to create')
    parser.add_argument('--page-index', type=int, metavar='IDX', default=-1,
        help='Index of template page where code is inserted (<0 counts from end)')
    parser.add_argument('--keylen', type=int, metavar='K', default=8,
        help='Random key length to use')
    parser.add_argument('--seed', type=int, metavar='S', default=None,
        help='Random seed to use for reproducible unique keys')
    parser.add_argument('--pattern', metavar='PAT', default='{key}',
        help='Pattern used to create QR code data for each key')
    parser.add_argument('--qr-size', type=float, default=1.5, metavar='S',
        help='Size of QR code (including white margin) in inches')
    parser.add_argument('--qr-offset', type=float, default=1.0, metavar='O',
        help='Offset of QR code from bottom of page in inches')
    parser.add_argument('--font', default='Montserrat-Regular.ttf',
        help='Name of truetype font to use for key labels')
    args = parser.parse_args()
    input_path = Path(args.template)
    if not input_path.exists():
        raise RuntimeError(f'Cannot read template file: "{input_path}".')
    if args.num_copies <= 0:
        raise ValueError('Argument num-copies must be > 0.')

    # Load the requested font.
    font = ImageFont.truetype(args.font, 16)

    # Generate random keys.
    gen = np.random.RandomState(args.seed)
    maxtries = 10
    keys = []
    while maxtries > 0 and len(np.unique(keys)) < args.num_copies:
        keys = gen.randint(10 ** args.keylen, size=args.num_copies)
        maxtries -= 1
    if maxtries == 0:
        raise RuntimeError(f'Cannot generate {args.num_copies} unique keys. Try increasing keylen from {args.keylen}.')
    fmt = f'{{key:0{args.keylen}d}}'
    keys = [fmt.format(key=key) for key in keys]
    keys_path = input_path.parent / (input_path.stem + '_keys.txt')
    with open(keys_path, 'w') as f:
        for key in keys:
            print(key, file=f)
    if args.verbose:
        print(f'Wrote {args.num_copies} unique keys to "{keys_path}".')

    # Prepare QR code data for each key.
    data = [args.pattern.format(key=key) for key in keys]

    # Check that we can read the template file and count the number of pages.
    with open(input_path, 'rb') as f:
        template = pypdf.PdfFileReader(f)
        npages = template.getNumPages()
    if args.verbose:
        print(f'Read "{args.template}" with {npages} page(s).')
    # Convert a negative index to a postive one if necessary.
    idx = list(range(npages))[args.page_index]
    if args.verbose:
        print(f'Codes will be inserted on page {idx + 1} of {npages}.')

    # Create each copy.
    for c in range(args.num_copies):

        # Generate a PDF with the QR code.
        basename = str(input_path.parent / (input_path.stem + f'_tmp_{c}'))
        save_qr_as_pdf(basename, data[c], args.qr_size, font)

        # Read the generated PDF.
        with open(basename + '.pdf', 'rb') as fin1:
            QR = pypdf.PdfFileReader(fin1).getPage(0)

            # Read the template.
            with open(input_path, 'rb') as fin2:
                template = pypdf.PdfFileReader(fin2)

                # Build this copy.
                writer = pypdf.PdfFileWriter()
                for p in range(npages):
                    page = template.getPage(p)
                    print(QR.mediaBox, page.mediaBox)
                    if p == idx:
                        page.mergeTranslatedPage(
                            QR, tx=0.5 * (page.mediaBox.getWidth() - QR.mediaBox.getWidth()),
                            ty=72 * args.qr_offset)
                    writer.addPage(page)

                # Save this copy.
                copy_path = input_path.parent / (input_path.stem + f'_{c}.pdf')
                with open(copy_path, 'wb') as fout:
                    writer.write(fout)

    # Combine copies.
    merger = pypdf.PdfFileMerger()
    open_files = []
    for c in range(args.num_copies):
        # All input files must remain open (!) until we write the merged output.
        copy_path = input_path.parent / (input_path.stem + f'_{c}.pdf')
        fin = open(copy_path, 'rb')
        open_files.append(fin)
        merger.append(fin)
    output_path = input_path.parent / (input_path.stem + '_rollcall.pdf')
    with open(output_path, 'wb') as fout:
        merger.write(fout)
    if args.verbose:
        print(f'Wrote {args.num_copies} x {npages} pages to "{output_path}".')


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print('ERROR:', e)
        traceback.print_exc(file=sys.stdout)
        sys.exit(-1)
